//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tạo mới danh mục.
        /// </summary>
        public static string Category_Create
        {
            get
            {
                return ResourceManager.GetString("Category_Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        public static string Category_Create_Button
        {
            get
            {
                return ResourceManager.GetString("Category_Create_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Category_DisplayOrder {
            get {
                return ResourceManager.GetString("Category_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả SEO.
        /// </summary>
        public static string Category_MetaDescriptions {
            get {
                return ResourceManager.GetString("Category_MetaDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string Category_MetaKeywords {
            get {
                return ResourceManager.GetString("Category_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Category_MetaTitle {
            get {
                return ResourceManager.GetString("Category_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục cha.
        /// </summary>
        public static string Category_ParentID {
            get {
                return ResourceManager.GetString("Category_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề seo.
        /// </summary>
        public static string Category_SeoTitle {
            get {
                return ResourceManager.GetString("Category_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string Category_ShowOnHome {
            get {
                return ResourceManager.GetString("Category_ShowOnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Category_Status {
            get {
                return ResourceManager.GetString("Category_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Menu_Category
        {
            get
            {
                return ResourceManager.GetString("Menu_Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quản lý chung.
        /// </summary>
        public static string Menu_GeneralManagement
        {
            get
            {
                return ResourceManager.GetString("Menu_GeneralManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Menu_Home
        {
            get
            {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string Menu_Newspaper
        {
            get
            {
                return ResourceManager.GetString("Menu_Newspaper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Menu_Product
        {
            get
            {
                return ResourceManager.GetString("Menu_Product", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        public static string Menu_System
        {
            get
            {
                return ResourceManager.GetString("Menu_System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string Menu_User
        {
            get
            {
                return ResourceManager.GetString("Menu_User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        public static string Menu_UserGroup
        {
            get
            {
                return ResourceManager.GetString("Menu_UserGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
